
development:
  adapter: postgresql
  encoding: utf8
  database: predios
  username: willfelix
  password: ninjadev
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: predios
  username: willfelix
  password: ninjadev
  host: localhost
